PL/Pages/Authentication/Authentication.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Authentication;
using DSL.Services.Declarations;

namespace PL.Pages.Authentication
{
    [BindProperties]
    public class AuthenticationModel(IAuthService service) : PageModel
    {
        private readonly IAuthService _service = service;

        public AuthenticationAdapter AuthData { get; set; } = new();

        public IActionResult OnGetRequestExternalSignIn(string provider, string returnUrl)
        {
            return Challenge(_service.GetXAuthProps(provider, returnUrl), provider);
        }

        public async Task<IActionResult> OnGetExternalSignInApprovedAsync()
        {
            if (await _service.ExternalSignInAsync())
            {
                return Redirect("/");
            }
            else return Redirect("/authentication");
        }

        public async Task<IActionResult> OnGetExternalSignInApprovedAndRedirectAsync(string ReturnUrl)
        {
            if (await _service.ExternalSignInAsync())
            {
                return Redirect(ReturnUrl);
            }
            else return RedirectToPage("/Authentication/Authentication",
                new { ReturnUrl });
        }

        public IActionResult OnGetSignOut()
        {
            Response.Cookies.Delete(".AspNetCore.Session");

            _service.SignOutAsync();

            return Redirect("/authentication");
        }

        public async Task<IActionResult> OnPostSignInAsync()
        {
            if (!ModelState.IsValid) return Page();

            if (await _service.InternalSignInAsync(AuthData))
            {
                return Redirect("/");
            }
            else return Page();
        }

        public async Task<IActionResult> OnPostAuthorizeAsync(string ReturnUrl)
        {
            if (!ModelState.IsValid) return Page();

            if (await _service.InternalSignInAsync(AuthData))
            {
                return Redirect(ReturnUrl);
            }
            else return RedirectToPage("/Authentication/Authentication",
                new { ReturnUrl });
        }
    }
}

PL/Pages/Authentication/Recovery.cshtml.cs
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Authentication;
using DSL.Services.Declarations;

namespace PL.Pages.Authentication
{
    [BindProperties]
    public class RecoveryModel(IAuthService service) : PageModel
    {
        private readonly IAuthService _service = service;

        public RecoveryRequestAdapter RecoveryData { get; set; } = new();
        public PasswordResetAdapter ResetData { get; set; } = new();

        public async Task<IActionResult> OnPostResetPassword()
        {
            await _service.EndPasswordRecoveryAsync(ResetData);

            return Redirect("/authentication");
        }

        public async Task<IActionResult> OnPostSendRecoveryMailAsync()
        {
            if (ModelState.IsValid)
            {
                return Redirect("/authentication");
            }

            await _service.BeginPasswordRecoveryAsync(RecoveryData, new Uri(Request.GetDisplayUrl()).GetLeftPart(UriPartial.Path),
                System.IO.File.ReadAllText("Pages/Mail/RecoveryMail.html"));

            return Redirect("/authentication");
        }
    }
}

PL/Pages/Authentication/Registration.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Authentication;
using DSL.Services.Declarations;

namespace PL.Pages.Authentication
{
    [BindProperties]
    public class RegistrationModel(IAuthService service) : PageModel
    {
        private readonly IAuthService _service = service;

        public RegistrationAdapter AuthData { get; set; } = new();
        public IEnumerable<AuthenticationScheme> Schemes { get; set; } = [];

        public async Task<IActionResult> OnPostRegisterAsync()
        {
            if (await _service.InternalSignUpAsync(AuthData))
            {
                return Redirect("/authentication");
            }
            else return null!;
        }
    }
}

PL/Pages/Authentication/Authentication.cshtml
@page
@model PL.Pages.Authentication.AuthenticationModel
@{
    string? returnUrl = Request.Query["ReturnUrl"];

    ViewData["PageTitle"] = "Authentication";
    Layout = "_Authentication";
}

<div class="container px-4 my-5">
    <div class="row auth-gap jc-sa ai-center">
        <div class="col-5">
            <div class="row my-5 mt-0">
                <div class="col ta-center">
                    <h3 class="min-md">Authentication</h3>
                </div>
            </div>

            <div class="row ai-center jc-center">
                <div class="col-0">
                    <i class="fa fa-info-circle fa-2xl clr-g mx-3"></i>
                </div>
                <div class="col info-separator ta-center">
                    <p>
                        Greetings, <strong>User</strong>! To sign in into your Account, use form on the right.
                        Provide your username and password.<br />
                        If you are here for first time, you need to register before. Follow link below.<br />
                        Or, follow second link and use your Google Account to sign in/sign up.
                        It will take a single click.
                    </p>
                </div>
            </div>
        </div>

        <div class="col-3 card p-4 my-5">
            <div class="row">
                <div class="col">
                    <form method="post" id="auth" autocomplete="off">
                        <div class="field">
                            <input type="text" class="input" id="reg-username" asp-for="AuthData.Username" />
                            <label class="label" for="reg-username">Username</label>

                            <span asp-validation-for="AuthData.Username"></span>
                        </div>

                        <div class="field">
                            <input type="password" class="input" id="reg-password" asp-for="AuthData.Password" />
                            <label class="label" for="reg-password">Password</label>

                            <span asp-validation-for="AuthData.Password"></span>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row my-3">
                <div class="col ta-center">
                    @if (returnUrl is not null)
                    {
                        <button class="button" form="auth" asp-page-handler="Authorize"
                                asp-route-ReturnUrl="@returnUrl">
                            Sign In
                        </button>
                    }
                    else
                    {
                        <button class="button" form="auth"
                                asp-page-handler="SignIn">
                            Sign In
                        </button>
                    }
                </div>
            </div>
            <div class="row my-3">
                <div class="col ta-center">
                    <a class="link" href="/recovery">Forgot password?</a>
                </div>
            </div>
            <div class="row my-3">
                <div class="col ta-center">
                    <a class="link" href="/registration">Have not an account? Sign Up</a>
                </div>
            </div>
            <hr class="my-3 px-5 mx-5" />
            <div class="row my-3">
                <div class="col ta-center">
                    @if (returnUrl is not null)
                    {
                        <a class="link" href="/authentication?handler=RequestExternalSignIn&provider=Google&returnUrl=/authentication?handler=ExternalSignInApprovedAndRedirect%26ReturnUrl=@returnUrl">Or, sign in with <i class="fa-brands fa-google"></i>oogle</a>
                    }
                    else
                    {
                        <a class="link" href="/authentication?handler=RequestExternalSignIn&provider=Google&returnUrl=/authentication?handler=ExternalSignInApproved">Or, sign in with <i class="fa-brands fa-google"></i>oogle</a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

PL/Pages/Authentication/Recovery.cshtml
@page
@model PL.Pages.Authentication.RecoveryModel
@{
    bool recoveryAllowed = Request.Query.ContainsKey("username")
    && Request.Query.ContainsKey("token");

    ViewData["PageTitle"] = "Password Recovery";
    Layout = "_Authentication";
}

<div class="container px-4 my-5">
    <div class="row auth-gap jc-sa ai-center">
        <div class="col-5">
            <div class="row my-5 mt-0">
                <div class="col ta-center">
                    <h3 class="min-md">Authentication</h3>
                </div>
            </div>

            <div class="row ai-center jc-center">
                <div class="col-0">
                    <i class="fa fa-info-circle fa-2xl clr-g mx-3"></i>
                </div>
                <div class="col info-separator ta-center">
                    @if (!recoveryAllowed)
                    {
                        <p>
                            Greetings, <strong>User</strong>! In case of password loss you can restore your access to Marketplace Account.<br />
                            To that, use form and enter your username. If it will be recognized correctly, we will send a letter on email,
                            connected to provided username. Use link from the mail, you will be returned to this page, after that you will be able to provide new password.
                        </p>
                    }
                    else
                    {
                        <p>
                            Greetings, <strong>User</strong>! You have last step behind to recovery your password. Provide new password to your Account.<br />
                            Remember to use strong password, no shorter than 12 symbols, and has it in handwritten form in safety place.
                        </p>
                    }
                </div>
            </div>
        </div>

        <div class="col-3 card p-4 my-5">
            <div class="row">
                <div class="col">
                    @if (!recoveryAllowed) {
                        <form method="post" id="auth" autocomplete="off">
                            <div class="field">
                                <input type="text" class="input" id="reg-username" asp-for="RecoveryData.Username" />
                                <label class="label" for="reg-username">Username</label>

                                <span asp-validation-for="RecoveryData.Username"></span>
                            </div>
                        </form>
                    }
                    else
                    {
                        <form method="post" id="auth" autocomplete="off">
                            <div class="field">
                                <input type="text" class="secret" value="@Request.Query["username"]"
                                    asp-for="ResetData.Username" />
                                <input type="text" class="secret" value="@Request.Query["token"].ToString().Replace(" ", "+")"
                                    asp-for="ResetData.Token" />
                            </div>

                            <div class="field">
                                <input type="password" class="input" id="reg-password" asp-for="ResetData.Password" />
                                <label class="label" for="reg-password">New Password</label>

                                <span asp-validation-for="ResetData.PassCheck"></span>
                            </div>

                            <div class="field">
                                <input type="password" class="input" id="reg-passcheck" asp-for="ResetData.PassCheck" />
                                <label class="label" for="reg-passcheck">Check Password</label>

                                <span asp-validation-for="ResetData.PassCheck"></span>
                            </div>
                        </form>
                    }
                </div>
            </div>

            <div class="row my-3">
                <div class="col ta-center">
                    @if (!recoveryAllowed)
                    {
                        <button class="button" form="auth" asp-page-handler="SendRecoveryMail">Recovery</button>
                    }
                    else
                    {
                        <button class="button" form="auth" asp-page-handler="ResetPassword"
                                asp-route-username="@Request.Query["username"]"
                                asp-route-token="@Request.Query["token"]">Recovery</button>
                    }
                </div>
            </div>
            <div class="row my-3">
                <div class="col ta-center">
                    <a class="link" href="/authentication">Return to Sign In page</a>
                </div>
            </div>
        </div>
    </div>
</div>

PL/Pages/Authentication/Registration.cshtml
@page
@model PL.Pages.Authentication.RegistrationModel
@{
    ViewData["PageTitle"] = "Registration";
    Layout = "_Authentication";
}

<div class="container px-4 my-5">
    <div class="row auth-gap jc-sa ai-center">
        <div class="col-5">
            <div class="row my-5 mt-0">
                <div class="col ta-center">
                    <h3 class="min-md">Registration</h3>
                </div>
            </div>

            <div class="row my-5 ai-center jc-center">
                <div class="col-0">
                    <i class="fa fa-info-circle fa-2xl clr-g mx-3"></i>
                </div>
                <div class="col info-separator ta-center">
                    <p>
                        Greetings, <strong>User</strong>! You have chosen to create your personal Account.<br />
                        Account is required for such actions as product ordering, evaluating, leaving feebacks, etc.<br />
                        We need you to provide some information about yourself before registeration...<br />
                        Or, if you already have an Account, follow link below to sign in page.
                    </p>
                </div>
            </div>

            <div class="row my-5 ai-center jc-center">
                <div class="col-0">
                    <i class="fa fa-info-circle fa-2xl clr-g mx-3"></i>
                </div>
                <div class="col info-separator ta-center">
                    <p>
                        1. Provide your actual name. It needs for order handling.<br />
                        2. Provide your email address. It will be an alternative way to make contact with you.<br />
                        3. Provide your actual phone number. It will be a way to make contact with you.<br />
                        4. Provide a username, that will be suitable for you.<br />
                        5. Provide a strong enough password.
                    </p>
                </div>
            </div>

            <div class="row my-5 ai-center jc-center">
                <div class="col-0">
                    <i class="fa fa-info-circle fa-2xl clr-r mx-3"></i>
                </div>
                <div class="col info-separator ta-center">
                    <p>
                        We highly recommend you to store your username and password in handwritten form.<br />
                        Password must contain at least one lowercase and one uppercase letter and be
                        12-th symbols long minimal.
                    </p>
                </div>
            </div>
        </div>

        <div class="col-3 card p-4 my-5">
            <div class="row">
                <div class="col">
                    <form method="post" id="reg" autocomplete="off">
                        <div class="field">
                            <input type="text" class="input" id="reg-firstname" asp-for="AuthData.Firstname" />
                            <label class="label" for="reg-firstname">Firstname</label>

                            <span asp-validation-for="AuthData.Firstname"></span>
                        </div>

                        <div class="field">
                            <input type="text" class="input" id="reg-lastname" asp-for="AuthData.Lastname" />
                            <label class="label" for="reg-lastname">Lastname</label>

                            <span asp-validation-for="AuthData.Lastname"></span>
                        </div>

                        <div class="field">
                            <input type="text" class="input" id="reg-email" asp-for="AuthData.Email" />
                            <label class="label" for="reg-email">Email</label>

                            <span asp-validation-for="AuthData.Email"></span>
                        </div>

                        <div class="field">
                            <input type="tel" class="input" id="reg-phone" asp-for="AuthData.PhoneNumber" />
                            <label class="label" for="reg-phone">Phone Number</label>

                            <span asp-validation-for="AuthData.PhoneNumber"></span>
                        </div>

                        <div class="field">
                            <input type="text" class="input" id="reg-username" asp-for="AuthData.UserName" />
                            <label class="label" for="reg-username">Username</label>

                            <span asp-validation-for="AuthData.UserName"></span>
                        </div>

                        <div class="field">
                            <input type="password" class="input" id="reg-password" asp-for="AuthData.Password" />
                            <label class="label" for="reg-password">Password</label>

                            <span asp-validation-for="AuthData.Password"></span>
                        </div>

                        <div class="field">
                            <input type="password" class="input" id="reg-check" asp-for="AuthData.PassCheck" />
                            <label class="label" for="reg-check">Repeat Password</label>

                            <span asp-validation-for="AuthData.PassCheck"></span>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row my-3">
                <div class="col ta-center">
                    <button class="button" form="reg" asp-page-handler="Register">Sign Up</button>
                </div>
            </div>
            <hr class="my-3 px-5 mx-5" />
            <div class="row">
                <div class="col ta-center">
                    <a class="link" href="/authentication">Already have an account? Sign In</a>
                </div>
            </div>
        </div>
    </div>
</div>