PL/Pages/Maintenance/Attribute/Editor.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Attribute;
using DSL.Adapters.Maintenance.Category;
using DSL.Adapters.Maintenance.Group;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Attribute
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class EditorModel(IAttributeService aService,
        IAttributeGroupService gService,
        ICategoryService cService) : PageModel
    {
        private readonly IAttributeService _aService = aService;
        private readonly IAttributeGroupService _gService = gService;
        private readonly ICategoryService _cService = cService;

        public AttributeRWAdapter Attribute { get; set; } = new();
        public List<AttributeGroupRWAdapter> Groups { get; set; } = [];
        public List<CategoryRAdapter> Categories { get; set; } = [];

        public bool KeyChecked { get; set; } = true;

        public void OnGet(string key)
        {
            if (key is null)
            {
                Groups.AddRange(_gService.GetGroups());
                Categories.AddRange(_cService.GetAttachableCategories());
            }
            else if (_aService.KeyCheck(key))
            {
                Attribute = _aService.GetAttribute(key);
                Groups.AddRange(_gService.GetGroups());
                Categories.AddRange(_cService.GetAttachableCategories());
            }
            else
            {
                KeyChecked = !KeyChecked;
            }
        }

        public IActionResult OnGetDrop(string key)
        {
            _aService.DropAttribute(key);

            return Redirect("/maintenance/attributes");
        }

        public IActionResult OnPostPush()
        {
            if (ModelState.IsValid)
                _aService.PushOrModifyAttribute(Attribute);

            return Redirect("/maintenance/attributes");
        }
    }
}

PL/Pages/Maintenance/Attribute/List.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Attribute;
using DSL.Adapters.Maintenance.Category;
using DSL.Adapters.Maintenance.Group;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Attribute
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class ListModel(IAttributeService aService,
        IAttributeGroupService gService,
        ICategoryService cService) : PageModel
    {
        private readonly IAttributeService _aService = aService;
        private readonly IAttributeGroupService _gService = gService;
        private readonly ICategoryService _cService = cService;

        public List<AttributeRAdapter> Attributes { get; set; } = [];
        public List<AttributeGroupRAdapter> Groups { get; set; } = [];
        public List<CategoryRAdapter> Categories { get; set; } = [];

        public void OnGet()
        {
            Attributes.AddRange(_aService.GetAttributesAsList());
            Groups.AddRange(_gService.GetGroupsAsList());
            Categories.AddRange(_cService.GetAttachableCategories());
        }
    }
}

PL/Pages/Maintenance/Category/Editor.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Category;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Category
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class EditorModel(ICategoryService service) : PageModel
    {
        private readonly ICategoryService _service = service;

        public CategoryRWAdapter Category { get; set; } = new();
        public List<CategoryRAdapter> Categories { get; set; } = [];

        public bool KeyChecked { get; set; } = true;

        public void OnGet(string key)
        {
            if (key is null)
            {
                Categories.AddRange(_service.GetPrimaryCategories());
            }
            else if (_service.KeyCheck(key))
            {
                Category = _service.GetCategory(key);
                Categories.AddRange(_service.GetPrimaryCategories(Category.Key));
            }
            else
            {
                KeyChecked = !KeyChecked;
            }
        }

        public IActionResult OnGetDrop(string key)
        {
            _service.DropCategory(key);

            return Redirect("/maintenance/categories");
        }

        public IActionResult OnPostPush()
        {
            if (ModelState.IsValid)
                _service.PushOrModifyCategory(Category);

            return Redirect("/maintenance/categories");
        }
    }
}

PL/Pages/Maintenance/Category/List.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Category;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Category
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class ListModel(ICategoryService service) : PageModel
    {
        private readonly ICategoryService _service = service;

        public List<CategoryRAdapter> Primaries { get; set; } = [];
        public List<CategoryRAdapter> Attached { get; set; } = [];

        public void OnGet()
        {
            Primaries.AddRange(_service.GetPrimaryCategories());
            Attached.AddRange(_service.GetAttachableCategories());
        }
    }
}

PL/Pages/Maintenance/Group/Editor.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Category;
using DSL.Adapters.Maintenance.Group;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Group
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class EditorModel(IAttributeGroupService gService,
        ICategoryService cService) : PageModel
    {
        private readonly IAttributeGroupService _gService = gService;
        private readonly ICategoryService _cService = cService;

        public AttributeGroupRWAdapter Group { get; set; } = new();
        public List<CategoryRAdapter> Categories { get; set; } = [];

        public bool KeyChecked { get; set; } = true;

        public void OnGet(string key)
        {
            if (key is null)
            {
                Categories.AddRange(_cService.GetAttachableCategories());
            }
            else if (_gService.KeyCheck(key))
            {
                Group = _gService.GetGroup(key);
                Categories.AddRange(_cService.GetAttachableCategories());
            }
            else
            {
                KeyChecked = !KeyChecked;
            }
        }

        public IActionResult OnGetDrop(string key)
        {
            _gService.DropGroup(key);

            return Redirect("/maintenance/groups");
        }

        public IActionResult OnPostPush()
        {
            if (ModelState.IsValid)
                _gService.PushOrModifyGroup(Group);

            return Redirect("/Maintenance/groups");
        }
    }
}

PL/Pages/Maintenance/Group/List.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Category;
using DSL.Adapters.Maintenance.Group;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Group
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class ListModel(IAttributeGroupService gService,
        ICategoryService cService) : PageModel
    {
        private readonly IAttributeGroupService _gService = gService;
        private readonly ICategoryService _cService = cService;

        public List<AttributeGroupRAdapter> Groups { get; set; } = [];
        public List<CategoryRAdapter> Categories { get; set; } = [];

        public void OnGet()
        {
            Groups.AddRange(_gService.GetGroupsAsList());
            Categories.AddRange(_cService.GetAttachableCategories());
        }
    }
}

PL/Pages/Maintenance/Maintenance.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DAL.Enums;

using DSL.Adapters.Maintenance.Order;
using DSL.Adapters.Maintenance.Product;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance
{
    [Authorize(Roles = "Administrator")]
    public class MaintenanceModel(IOrderService orderService,
        IProductService productService,
        IAuthService authService,
        ISupplyService supplyService) : PageModel
    {
        private readonly IOrderService _orderService = orderService;
        private readonly IProductService _productService = productService;
        private readonly IAuthService _authService = authService;
        private readonly ISupplyService _supplyService = supplyService;

        public List<OrderRAdapter> Orders { get; set; } = [];
        public List<ShortOrderAdapter> Products { get; set; } = [];

        public async Task OnGet(OrderProcessingState os)
        {
            Orders.AddRange(_orderService.GetOrders(os));
            Products.AddRange(_productService.GetProducts(Orders.Select(s => s.AttachedProduct)!));

            foreach (OrderRAdapter order in Orders)
            {
                order.AttachedUsername = await _authService.GetFullname(order.AttachedUsername);
            }
        }

        public IActionResult OnPostNextState(string key, OrderProcessingState state)
        {
            _orderService.NextState(key, ++state);

            return Redirect($"/maintenance/{(int)state}");
        }

        public IActionResult OnPostComplete(string key, string url)
        {
            OrderRAdapter order = _orderService.GetOrder(key);

            if (_orderService.StoreOrder(key, OrderCompletionState.Completed))
            {
                _orderService.RemoveOrder(key);
            }

            return Redirect(url);
        }

        public IActionResult OnPostRevoke(string key, string url)
        {
            OrderRAdapter order = _orderService.GetOrder(key);

            if (_supplyService.RestoreAmount(order.AttachedProduct, order.Amount))
            {
                _orderService.StoreOrder(key, OrderCompletionState.Revoked);
                _orderService.RemoveOrder(key);
            }

            return Redirect(url);
        }
    }
}

PL/Pages/Maintenance/Product/Editor.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Attribute;
using DSL.Adapters.Maintenance.Category;
using DSL.Adapters.Maintenance.Group;
using DSL.Adapters.Maintenance.Product;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Product
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class EditorModel(IProductService pService,
        ICategoryService cService,
        IAttributeGroupService gService,
        ISupplyService sService) : PageModel
    {
        private readonly IProductService _pService = pService;
        private readonly ICategoryService _cService = cService;
        private readonly IAttributeGroupService _gService = gService;
        private readonly ISupplyService _sService = sService;

        public List<CategoryRAdapter> Categories { get; set; } = [];
        public List<AttributeGroupXRAdapter> Groups { get; set; } = [];
        public ProductRWAdapter Product { get; set; } = new();
        [BindNever]
        public CategoryRWAdapter CurrentCategory { get; set; } = new();

        public bool KeyChecked { get; set; } = true;

        public void OnGet(string ckey, string pkey)
        {
            if (pkey is null)
            {
                Groups.AddRange(_gService.GetGroupsByCategory(ckey));
                CurrentCategory = _cService.GetCategory(ckey);

                Extend();
            }
            else if (_pService.KeyCheck(pkey))
            {
                Groups.AddRange(_gService.GetGroupsByCategory(ckey));
                Product = _pService.GetProduct(pkey);

                CurrentCategory = _cService.GetCategory(ckey);

                ExtendWithKey();
            }
            else
            {
                KeyChecked = !KeyChecked;
            }
        }

        public IActionResult OnGetDrop(string ckey, string pkey)
        {
            _pService.DropProduct(pkey);

            return Redirect("/maintenance/products/" + ckey);
        }

        public IActionResult OnPostPush(string ckey)
        {
            if (ModelState.IsValid)
            {
                SupplyWAdapter adapter = new()
                {
                    Key = Guid.NewGuid().ToString(),
                    Amount = Product.Amount,
                    OfCategory = Product.AttachedToCategory,
                    AttachedProduct = Product.Key
                };

                _pService.PushOrModifyProduct(Product);
                _sService.CreateAmount(adapter);
            }

            return Redirect("/maintenance/products/" + ckey);
        }

        public void Extend()
        {
            foreach (AttributeGroupXRAdapter group in Groups)
            {
                foreach (ProductAttributeXRWAdapter attribute in group.AttachedAttributes)
                {
                    Product.AttachedValues.Add(new());
                }
            }
        }

        public void ExtendWithKey()
        {
            foreach (AttributeGroupXRAdapter group in Groups)
            {
                foreach (ProductAttributeXRWAdapter attribute in group.AttachedAttributes)
                {
                    if (!Product.AttachedValues
                        .Any(p => p.AttachedToAttribute == attribute.Key))
                    {
                        Product.AttachedValues
                            .Add(new() { AttachedToAttribute = attribute.Key });
                    }
                }
            }
        }
    }
}

PL/Pages/Maintenance/Product/List.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Category;
using DSL.Adapters.Maintenance.Product;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Product
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class ListModel(IProductService pService,
        ICategoryService cService) : PageModel
    {
        private readonly IProductService _pService = pService;
        private readonly ICategoryService _cService = cService;

        public List<ProductRAdapter> Products { get; set; } = [];
        public List<CategoryRAdapter> Categories { get; set; } = [];

        public string? CurrentCategory { get; set; }
        public int ProductsCount { get; set; }

        public void OnGet(string key)
        {
            if (key is not null)
            {
                Products.AddRange(_pService.GetProductsOfCategory(key));

                CurrentCategory = key;
            }

            ProductsCount = _pService.GetCount();
            Categories.AddRange(_cService.GetAttachableCategories());
        }
    }
}

PL/Pages/Maintenance/Supply.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Category;
using DSL.Adapters.Maintenance.Product;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance
{
    [BindProperties]
    public class SupplyModel(ICategoryService cService,
        IProductService pService,
        ISupplyService sService) : PageModel
    {
        private readonly ICategoryService _cService = cService;
        private readonly IProductService _pService = pService;
        private readonly ISupplyService _sService = sService;

        public List<CategoryRAdapter> Categories { get; set; } = [];
        public List<SupplyRAdapter> SupplyList { get; set; } = [];

        public void OnGet(string key)
        {
            if (_cService.KeyCheck(key))
            {
                SupplyList.AddRange(_sService.GetSupplyList(key));

                IEnumerable<KeyValuePair<string, string>> prods
                    = _pService.GetProductNames(SupplyList.Select(s => s.AttachedProduct));

                SupplyList.ForEach(a
                    => a.AttachedProduct = prods.Single(p => p.Key == a.AttachedProduct).Value);
            }

            Categories.AddRange(_cService.GetAttachableCategories());
        }

        public IActionResult OnPostUpdateSupplyList(string key)
        {
            _sService.SetAmount(SupplyList.AsEnumerable());

            return Redirect("/maintenance/supply/" + key);
        }
    }
}

PL/Pages/Maintenance/Maintenance.cshtml
@page "{os:int=0}"
@model PL.Pages.Maintenance.MaintenanceModel
@{
    Layout = "_Maintenance";
    ViewData["PageTitle"] = "Maintenance";
}

@using DAL.Enums

<div class="container px-4 my-5">
    <div class="row ai-center">
        <div class="col-0">
            <i class="fa fa-info-circle fa-2xl clr-g mx-3"></i>
        </div>

        <div class="col my-3">
            <h3>
                Here stores all orders that are waiting for processing.
            </h3>
        </div>
    </div>

    <div class="row">
        <div class="col my-3 ta-end">
            <p>
                <strong>@Model.Products.Count</strong> active @(Model.Products.Count == 1 ? "order" : "orders") pending
            </p>
        </div>
    </div>
</div>

<div class="container px-4 my-5">
    <div class="row g-5">
        <div class="col min-sm">
            <div class="row g-3 jc-center">
                <div class="col-0">
                    @if (Model.RouteData.Values["os"]!.Equals("0"))
                    {
                        <p class="clr-b">@OrderProcessingState.Registered</p>
                    }
                    else
                    {
                        <a href="/maintenance" class="link">@OrderProcessingState.Registered</a>
                    }
                </div>

                <div class="col-0">
                    @if (Model.RouteData.Values["os"]!.Equals("1"))
                    {
                        <p class="clr-b">@OrderProcessingState.Accepted</p>
                    }
                    else
                    {
                        <a href="/maintenance/1" class="link">@OrderProcessingState.Accepted</a>
                    }
                </div>

                <div class="col-0">
                    @if (Model.RouteData.Values["os"]!.Equals("2"))
                    {
                        <p class="clr-b">@OrderProcessingState.Sent</p>
                    }
                    else
                    {
                        <a href="/maintenance/2" class="link">@OrderProcessingState.Sent</a>
                    }
                </div>

                <div class="col-0">
                    @if (Model.RouteData.Values["os"]!.Equals("3"))
                    {
                        <p class="clr-b">@OrderProcessingState.Delivered</p>
                    }
                    else
                    {
                        <a href="/maintenance/3" class="link">@OrderProcessingState.Delivered</a>
                    }
                </div>
            </div>
        </div>

        <div class="col min-sm">
            <div class="row g-3 jc-center">
                <div class="col-0">
                    <a href="/storage/0" class="link">@OrderCompletionState.Completed</a>
                </div>

                <div class="col-0">
                    <a href="/storage/1" class="link">@OrderCompletionState.Revoked</a>
                </div>
            </div>
        </div>
    </div>

    <hr class="my-3" />
</div>

<div class="container px-4 my-5">
    @if (Model.Orders.Count == 0)
    {
        <div class="row">
            <div class="col ta-center">
                <p>No records</p>
            </div>
        </div>
    }
    @for (int idx = 0; idx < Model.Orders.Count; idx++)
    {
        <div class="card p-4">
            <div class="row">
                <div class="col">
                    <p class="clr-b">@Model.Orders[idx].OrderNo</p>
                </div>
                <div class="col ta-end">
                    <p class="clr-b">@Model.Orders[idx].WhenOrdered</p>
                </div>
            </div>
            <hr />
            <div class="row my-3 ai-center">
                <div class="col min-sm">
                    <div class="row g-3">
                        <div class="col">
                            <h3>Product</h3>
                        </div>
                        <div class="col">
                            <p>@Model.Products[idx].Product</p>
                        </div>
                    </div>

                    <div class="row g-3">
                        <div class="col">
                            <h3>Price</h3>
                        </div>
                        <div class="col">
                            <p>@Model.Products[idx].Price</p>
                        </div>
                    </div>

                    <div class="row g-3">
                        <div class="col">
                            <h3>Ordered Amount</h3>
                        </div>
                        <div class="col">
                            <p>@Model.Orders[idx].Amount</p>
                        </div>
                    </div>

                    <div class="my-3">
                        <div class="row g-3">
                            <div class="col">
                                <h3>Holder</h3>
                            </div>
                            <div class="col">
                                <p>@Model.Orders[idx].AttachedUsername</p>
                            </div>
                        </div>

                        <div class="row g-3">
                            <div class="col">
                                <h3>Shippment address</h3>
                            </div>
                            <div class="col">
                                <p>@Model.Orders[idx].Address</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="row jc-center my-3 g-3">
                        <div class="col-0">
                            <a class="button" href="/product/@Model.Products[idx].Key">View Product</a>
                        </div>

                        @if (Model.RouteData.Values["os"]!.Equals("3"))
                        {
                            <div class="col-0">
                                <form method="post" id="complete">
                                    <input type="password" value="@Model.Orders[idx].Key" name="key" class="secret" />
                                    <input type="password" value="/maintenance/@Model.RouteData.Values["os"]"
                                           name="url" class="secret" />
                                </form>
                                <button class="button" form="complete"
                                        formaction="/maintenance?handler=Complete">
                                    Complete
                                </button>
                            </div>
                        }
                        else
                        {
                            <div class="col-0">
                                <form method="post" id="next">
                                    <input type="password" value="@Model.Orders[idx].Key" name="key" class="secret" />
                                    <input type="password" value="@RouteData.Values["os"]" name="state" class="secret" />
                                </form>
                                <button class="button" form="next" formaction="/maintenance/@Model.RouteData.Values["os"]?handler=NextState">Next Stage</button>
                            </div>
                        }

                        <div class="col-0">
                            <form method="post" id="revoke">
                                <input type="password" value="@Model.Orders[idx].Key" name="key" class="secret" />
                                <input type="password" value="/maintenance/@Model.RouteData.Values["os"]"
                                    name="url" class="secret" />
                            </form>
                            <button class="button warning" form="revoke" 
                                formaction="/maintenance?handler=Revoke">Revoke</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

PL/Pages/Maintenance/Supply.cshtml
@page
@model PL.Pages.Maintenance.SupplyModel
@{
    bool categorySelected = Request.RouteValues["key"] != null;

    ViewData["PageTitle"] = "Product Supply Screening";
    Layout = "_Maintenance";
}

@using DSL.Adapters.Maintenance.Category

<div class="container px-4 my-5">
    <div class="row ai-center">
        <div class="col-0">
            <i class="fa fa-info-circle fa-2xl clr-g mx-3"></i>
        </div>

        <div class="col my-3">
            <h3>
                Watch and control product amount in Storage from here.
            </h3>
        </div>
    </div>

    <div class="row">
        <div class="col my-3 ta-end">
            <p>
                <strong>@Model.SupplyList.Count</strong> active @(Model.SupplyList.Count == 1 ? "product" : "products"), registered in Storage
            </p>
        </div>
    </div>
</div>

@if (categorySelected)
{
    @if (Model.SupplyList.Count != 0)
    {
        <div class="container px-4 my-5">
            <form method="post" id="viewer">
                @for (int idx = 0; idx < Model.SupplyList.Count; idx++)
                {
                    <div class="row card p-3 my-3 ai-center">
                        <div class="col ta-center">
                            <p>@Model.SupplyList[idx].AttachedProduct</p>
                        </div>
                        <div class="col my-3">
                            <div class="field m-0">
                                <input type="password" class="secret" value="@Model.SupplyList[idx].Key"
                                asp-for="@Model.SupplyList[idx].Key" />
                                <input type="text" class="input" asp-for="@Model.SupplyList[idx].Amount" />
                            </div>
                        </div>
                        <div class="col ta-center">
                            @if (Model.SupplyList[idx].Amount > 10)
                            {
                                <p class="clr-g">Available</p>
                            }
                            else if (Model.SupplyList[idx].Amount <= 10 && Model.SupplyList[idx].Amount > 0)
                            {
                                <p class="clr-o">Running Out</p>
                            }
                            else if (Model.SupplyList[idx].Amount == 0)
                            {
                                <p class="clr-r">Out of Storage</p>
                            }
                        </div>
                    </div>
                }
            </form>
        </div>
    }
    else
    {
        <div class="container px-5 my-5">
            <div class="row my-3">
                <div class="col ta-center">
                    <p>No products located in Storage</p>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="container px-4 my-5">
        <div class="row">
            <div class="col my-3 ta-center">
                <h3>
                    Use selection menu below to load all products, attached to selected category
                </h3>
            </div>
        </div>
    </div>
}

<div class="container px-4 my-5">
    <div class="row jc-center">
        <div class="col-0 my-1 mx-3 menu" data-component="menu">
            <button type="button" class="button">
                <p class="insertable">Choose category</p>
                <i class="fa fa-angle-down fa-sm"></i>
            </button>
            <div class="menu-list">
                @foreach (CategoryRAdapter category in Model.Categories)
                {
                    <a href="/maintenance/supply/@category.Key"
                       data-node="ns" class="menu-node">@category.Category</a>
                }
            </div>
        </div>
        @if (categorySelected)
        {
            <div class="col-0 my-1 mx-3">
                <button class="button" form="viewer" asp-route-key="@Request.RouteValues["key"]"
                        asp-page-handler="UpdateSupplyList">
                    Update
                </button>
            </div>
        }
    </div>
</div>