PL/Pages/Client/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Order;
using DSL.Adapters.Maintenance.Product;
using DSL.Services.Declarations;
using Microsoft.AspNetCore.Authorization;

namespace PL.Pages.Client
{
    [Authorize(Roles = "Customer, Administrator")]
    [BindProperties]
    public class CartModel(ISessionService session,
        IProductService pService,
        IOrderService oService,
        ISupplyService sService) : PageModel
    {
        private readonly ISessionService _session = session;
        private readonly IProductService _pService = pService;
        private readonly IOrderService _oService = oService;
        private readonly ISupplyService _sService = sService;

        public OrderWAdapter Order { get; set; } = new();
        public List<ProductRAdapter> Products { get; set; } = [];
        public SupplementaryOA Info { get; set; } = new();

        public void OnGet()
        {
            List<OrderWAdapter>? infos = _session.Get<List<OrderWAdapter>>(HttpContext.Session, "preorder");

            if (infos is not null)
            {
                foreach (OrderWAdapter info in infos)
                {
                    Products.Add(_pService.GetProductInfo(info.AttachedProduct!));
                }
            }
        }

        public IActionResult OnPostCreate()
        {
            List<OrderWAdapter>? infos = _session.Get<List<OrderWAdapter>>(HttpContext.Session, "preorder")!;
            OrderWAdapter info = infos.Find(p => p.AttachedProduct == Info.AttachedProduct)!;

            info.Address = Info.Address;
            info.Amount = Info.Amount;

            if (_sService.PreserveAmount(info.AttachedProduct!, Info.Amount))
            {
                _oService.MakeOrder(info);

                infos.Remove(info);
                HttpContext.Session.Remove("preorder");
                _session.Set(HttpContext.Session, "preorder", infos);
            }

            return Redirect("/cart");
        }

        public IActionResult OnGetDecline(string key)
        {
            List<OrderWAdapter> infos = _session.Get<List<OrderWAdapter>>(HttpContext.Session, "preorder")!;
            OrderWAdapter info = infos.Find(p => p.AttachedProduct == key)!;

            infos.Remove(info);

            HttpContext.Session.Remove("preorder");
            _session.Set(HttpContext.Session, "preorder", infos);

            return Redirect("/cart");
        }
    }
}

PL/Pages/Client/Catalog.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;

using DSL.Adapters.Maintenance.Product;
using DSL.Adapters.Maintenance.Category;
using DSL.Services.Declarations;
using DSL.Adapters.Maintenance.Order;

namespace PL.Pages.Client
{
    [BindProperties]
    public class ListModel(ISessionService session,
        IProductService pService,
        ICategoryService cService,
        IAttributeService aService) : PageModel
    {
        private readonly ISessionService _session = session;
        private readonly IProductService _pService = pService;
        private readonly ICategoryService _cService = cService;
        private readonly IAttributeService _aService = aService;

        public List<KeyValuePair<string, string>> AttributeNames { get; set; } = [];
        public List<KeyValuePair<string, bool>> FilterStorage { get; set; } = [];
        public List<KeyValuePair<string, string>> AttributeValues { get; set; } = [];
        public List<string> AttributeKeys { get; set; } = [];
        public List<ProductRAdapter> Products { get; set; } = [];
        public CategoryRWAdapter Category { get; set; } = new ();

        public void OnGet(string key, string filter)
        {
            Category = _cService.GetCategory(key);

            if (_pService.GetCountOfCategory(key) == 0) return;
            AttributeNames.AddRange(_aService.GetFilteredAttributesNames(key));
            AttributeValues.AddRange(_aService
                .GetFiltersValues(_aService
                .GetFilteredAttributes(_pService
                .GetRelatedAttributeKeys(key))));

            foreach (var item in AttributeValues)
            {
                if (AttributeKeys.Contains(item.Key)) continue;
                else AttributeKeys.Add(item.Key);
            }

            foreach (var item in AttributeKeys)
            {
                foreach (var item2 in AttributeValues.Where(p => p.Key == item))
                    FilterStorage.Add(new KeyValuePair<string, bool>(item2.Value, false));
            }

            if (filter is null)
            {
                Products.AddRange(_pService.GetProductsOfCategory(key));
            }
            else
            {
                Dictionary<string, List<string>> container = [];

                foreach (var item in filter.Split("-"))
                    FilterStorage[FilterStorage.IndexOf(FilterStorage.Find(p => p.Key == item))] = new KeyValuePair<string, bool>(item, true);

                foreach (var item in AttributeKeys) container.Add(AttributeValues.Find(p => p.Key == item).Key, []);
                foreach (var item in FilterStorage)
                {
                    if (item.Value)
                    {
                        container[AttributeValues.Find(p => p.Value == item.Key).Key].Add(item.Key);
                    }
                }
                foreach (var item in container)
                {
                    if (item.Value.Count == 0) container.Remove(item.Key);
                }

                Products.AddRange(_pService.GetProductsOfCategoryWithFilter(key, container.Select(p => p.Value)));
            }
        }

        public IActionResult OnGetPush(string key, string ctg)
        {
            List<OrderWAdapter>? infos = _session.Get<List<OrderWAdapter>>(HttpContext.Session, "preorder");
            OrderWAdapter pre = new()
            {
                Key = Guid.NewGuid().ToString(),
                AttachedProduct = key,
                AttachedUsername = User.Identity!.Name
            };

            if (User.Identity.IsAuthenticated)
            {
                if (infos is null)
                {
                    infos = [pre];

                    _session.Set(HttpContext.Session, "preorder", infos);
                }
                else
                {
                    infos.Add(pre);

                    HttpContext.Session.Remove("preorder");
                    _session.Set(HttpContext.Session, "preorder", infos);
                }
            }
            else return Redirect("/authentication?ReturnUrl=%2Fcatalog%2F" + ctg);

            return Redirect("/catalog/" + ctg);
        }

        public IActionResult OnPostFilter()
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendJoin("-", FilterStorage.Where(p => p.Value).Select(s => s.Key));

            return RedirectToPage("Catalog", new { key = RouteData.Values["key"],
                filter = builder.ToString() });
        }
    }
}

PL/Pages/Client/Categories.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Category;
using DSL.Services.Declarations;

namespace PL.Pages.Client
{
    public class CatalogModel(ICategoryService cService,
        IProductService pService) : PageModel
    {
        private readonly ICategoryService _cService = cService;
        private readonly IProductService _pService = pService;

        public List<CategoryRAdapter> Primaries { get; set; } = [];
        public List<CategoryRAdapter> Attached { get; set; } = [];

        public void OnGet()
        {
            Primaries.AddRange(_cService.GetPrimaryCategories());
            Attached.AddRange(_cService.GetAttachableCategories());

            foreach (CategoryRAdapter category in Attached)
                category.AttachedProducts = _pService.GetCountOfCategory(category.Key);
        }
    }
}

PL/Pages/Client/Orders.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Order;
using DSL.Adapters.Maintenance.Product;
using DSL.Services.Declarations;

namespace PL.Pages.Client
{
    [Authorize(Roles = "Customer, Administrator")]
    [BindProperties]
    public class OrdersModel(IOrderService orderService,
        IProductService productService,
        ISupplyService supplyService,
        IAuthService authService) : PageModel
    {
        private readonly IOrderService _orderService = orderService;
        private readonly IProductService _productService = productService;
        private readonly ISupplyService _supplyService = supplyService;
        private readonly IAuthService _authService = authService;

        public List<OrderRAdapter> Orders { get; set; } = [];
        public List<ShortOrderAdapter> Products { get; set; } = [];

        public async Task OnGetAsync()
        {
            ViewData["Holder"] = await _authService.GetFullname(User.Identity!.Name!);

            Orders.AddRange(_orderService.GetOrders(User.Identity!.Name!));
            Products.AddRange(_productService.GetProducts(Orders.Select(s => s.AttachedProduct)!));
        }

        public IActionResult OnPostDecline(string key)
        {
            OrderRAdapter order = _orderService.GetOrder(key);

            _orderService.RemoveOrder(key);
            _supplyService.RestoreAmount(order.AttachedProduct, order.Amount);

            return Redirect("/orders");
        }
    }
}

PL/Pages/Client/Product.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Group;
using DSL.Adapters.Maintenance.Order;
using DSL.Adapters.Maintenance.Product;
using DSL.Services.Declarations;

namespace PL.Pages.Client
{
    [BindProperties]
    public class ViewModel(ISessionService session,
        IProductService pService,
        IAttributeGroupService gService,
        ISupplyService sService) : PageModel
    {
        private readonly ISessionService _session = session;
        private readonly IProductService _pService = pService;
        private readonly IAttributeGroupService _gService = gService;
        private readonly ISupplyService _sService = sService;

        public ProductRWAdapter Product = new();
        public List<AttributeGroupXRAdapter> Groups { get; set; } = [];
        public int Amount { get; set; }

        public void OnGet(string key)
        {
            Product = _pService.GetProduct(key);
            Groups.AddRange(_gService.GetGroupsByCategory(Product.AttachedToCategory));
            Amount = _sService.GetSupplyRecord(key).Amount;

            List<OrderWAdapter>? infos = _session.Get<List<OrderWAdapter>>(HttpContext.Session, "preorder");

            if (infos is null)
            {
                ViewData["AllowOrdering"] = true;
                return;
            }

            OrderWAdapter? info = infos!.Find(p => p.AttachedProduct == Product.Key);

            if (info is null) ViewData["AllowOrdering"] = true;
            else ViewData["AllowOrdering"] = info!.AttachedUsername != User.Identity!.Name;
        }

        public IActionResult OnGetPush(string key)
        {
            List<OrderWAdapter>? infos = _session.Get<List<OrderWAdapter>>(HttpContext.Session, "preorder");
            OrderWAdapter pre = new()
            {
                Key = Guid.NewGuid().ToString(),
                AttachedProduct = key,
                AttachedUsername = User.Identity!.Name
            };

            if (User.Identity.IsAuthenticated)
            {
                if (infos is null)
                {
                    infos = [pre];

                    _session.Set(HttpContext.Session, "preorder", infos);
                }
                else
                {
                    infos.Add(pre);

                    HttpContext.Session.Remove("preorder");
                    _session.Set(HttpContext.Session, "preorder", infos);
                }
            }
            else return Redirect($"/authentication?ReturnUrl=%2Fproduct%2F{key}");

            return Redirect($"/product/{key}");
        }
    }
}

PL/Pages/Maintenance/Product/Editor.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Attribute;
using DSL.Adapters.Maintenance.Category;
using DSL.Adapters.Maintenance.Group;
using DSL.Adapters.Maintenance.Product;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Product
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class EditorModel(IProductService pService,
        ICategoryService cService,
        IAttributeGroupService gService,
        ISupplyService sService) : PageModel
    {
        private readonly IProductService _pService = pService;
        private readonly ICategoryService _cService = cService;
        private readonly IAttributeGroupService _gService = gService;
        private readonly ISupplyService _sService = sService;

        public List<CategoryRAdapter> Categories { get; set; } = [];
        public List<AttributeGroupXRAdapter> Groups { get; set; } = [];
        public ProductRWAdapter Product { get; set; } = new();
        [BindNever]
        public CategoryRWAdapter CurrentCategory { get; set; } = new();

        public bool KeyChecked { get; set; } = true;

        public void OnGet(string ckey, string pkey)
        {
            if (pkey is null)
            {
                Groups.AddRange(_gService.GetGroupsByCategory(ckey));
                CurrentCategory = _cService.GetCategory(ckey);

                Extend();
            }
            else if (_pService.KeyCheck(pkey))
            {
                Groups.AddRange(_gService.GetGroupsByCategory(ckey));
                Product = _pService.GetProduct(pkey);

                CurrentCategory = _cService.GetCategory(ckey);

                ExtendWithKey();
            }
            else
            {
                KeyChecked = !KeyChecked;
            }
        }

        public IActionResult OnGetDrop(string ckey, string pkey)
        {
            _pService.DropProduct(pkey);

            return Redirect("/maintenance/products/" + ckey);
        }

        public IActionResult OnPostPush(string ckey)
        {
            if (ModelState.IsValid)
            {
                SupplyWAdapter adapter = new()
                {
                    Key = Guid.NewGuid().ToString(),
                    Amount = Product.Amount,
                    OfCategory = Product.AttachedToCategory,
                    AttachedProduct = Product.Key
                };

                _pService.PushOrModifyProduct(Product);
                _sService.CreateAmount(adapter);
            }

            return Redirect("/maintenance/products/" + ckey);
        }

        public void Extend()
        {
            foreach (AttributeGroupXRAdapter group in Groups)
            {
                foreach (ProductAttributeXRWAdapter attribute in group.AttachedAttributes)
                {
                    Product.AttachedValues.Add(new());
                }
            }
        }

        public void ExtendWithKey()
        {
            foreach (AttributeGroupXRAdapter group in Groups)
            {
                foreach (ProductAttributeXRWAdapter attribute in group.AttachedAttributes)
                {
                    if (!Product.AttachedValues
                        .Any(p => p.AttachedToAttribute == attribute.Key))
                    {
                        Product.AttachedValues
                            .Add(new() { AttachedToAttribute = attribute.Key });
                    }
                }
            }
        }
    }
}

PL/Pages/Maintenance/Product/List.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using DSL.Adapters.Maintenance.Category;
using DSL.Adapters.Maintenance.Product;
using DSL.Services.Declarations;

namespace PL.Pages.Maintenance.Product
{
    [Authorize(Roles = "Administrator")]
    [BindProperties]
    public class ListModel(IProductService pService,
        ICategoryService cService) : PageModel
    {
        private readonly IProductService _pService = pService;
        private readonly ICategoryService _cService = cService;

        public List<ProductRAdapter> Products { get; set; } = [];
        public List<CategoryRAdapter> Categories { get; set; } = [];

        public string? CurrentCategory { get; set; }
        public int ProductsCount { get; set; }

        public void OnGet(string key)
        {
            if (key is not null)
            {
                Products.AddRange(_pService.GetProductsOfCategory(key));

                CurrentCategory = key;
            }

            ProductsCount = _pService.GetCount();
            Categories.AddRange(_cService.GetAttachableCategories());
        }
    }
}

PL/Pages/Client/Cart.cshtml
@page "{key?}"
@model PL.Pages.Client.CartModel
@{
    ViewData["PgTitle"] = "Cart";
    Layout = "_Marketplace";
}

@using DSL.Adapters.Maintenance.Product

<div class="container px-4 my-5">
    <div class="row ai-center">
        <div class="col-0">
            <i class="fa fa-info-circle fa-2xl clr-g mx-3"></i>
        </div>

        <div class="col my-3">
            <h3>
                Here all products you have interested to purchase.
            </h3>
        </div>
    </div>

    <div class="row">
        <div class="col my-3 ta-end">
            <p>
                There was <strong>@Model.Products.Count</strong> products, awaiting for ordering
            </p>
        </div>
    </div>
</div>

@if (Model.Products.Count > 0) {
    foreach (ProductRAdapter product in Model.Products)
    {
        <div class="container px-4 my-5">
            <div class="card p-4">
                <div class="row ai-center">
                    <div class="col">
                        <div class="row">
                            <div class="col">
                                <h2>Product</h2>
                            </div>

                            <div class="col">
                                <p>@product.Product</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <h2>Price</h2>
                            </div>

                            <div class="col">
                                <p>@product.Price<i class="fa fa-hryvnia fa-sm"></i></p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <form method="post" id="form" autocomplete="off">
                                    <div class="field m-0">
                                        <input type="password" class="secret" value="@product.Key" asp-for="Info.AttachedProduct" />
                                        <input type="text" class="input my-2"
                                            placeholder="Enter postal operator address" asp-for="Info.Address" />
                                        
                                        <span asp-validation-for="Info.Address"></span>
                                    </div>
                                    <div class="field m-0">
                                        <input type="number" class="input my-2"
                                               min="1" max="5" value="1" asp-for="Info.Amount" />
                                               
                                        <span asp-validation-for="Info.Amount"></span>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row jc-center">
                            <div class="col-0">
                                <button class="button mx-3" form="form" asp-page-handler="Create">Order</button>
                            </div>

                            <div class="col-0">
                                <a class="button warning" href="/cart/@product.Key?handler=Decline">Decline</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="container px-4 my-5">
        <div class="row">
            <div class="col ta-center">
                <p>Empty</p>
            </div>
        </div>
    </div>
}

<div class="container px-4 my-5">
    <div class="row">
        <div class="col ta-center">
            <p>Average price for all selected products - 
                <strong>@Model.Products.Sum(s => s.Price)<i class="fa fa-hryvnia fa-sm"></i></strong></p>
        </div>
    </div>
</div>

PL/Pages/Client/Catalog.cshtml
@page "{key}/{filter?}"
@model PL.Pages.Client.ListModel
@{
    ViewData["PageTitle"] = "View Products";
    Layout = "_Marketplace";
}

@using DSL.Adapters.Maintenance.Product

<div class="container px-4 my-5">
    <div class="row ai-center">
        <div class="col-0">
            <i class="fa fa-info-circle fa-2xl clr-g mx-3"></i>
        </div>

        <div class="col my-3">
            <h3>
                Here all products had found for category @Model.Category.Category<br />
                View list for interested products, and go for details or use filters
            </h3>
        </div>
    </div>

    <div class="row">
        <div class="col my-3 ta-end">
            <p>
                There was <strong>@Model.Products.Count</strong> product/s found
            </p>
        </div>
    </div>
</div>

@if (Model.Products.Count != 0)
{
    <div class="container px-4 my-5">
        <div class="row">
            <div class="col ta-center">
                <h3>Filter set</h3>
            </div>
        </div>

        <form method="post" id="filter">
            @{
                int idx = 0;

                foreach (var item in Model.AttributeKeys)
                {
                    <div class="row my-3 ai-center">
                        <div class="col">
                            <h3>@Model.AttributeNames.Find(p => p.Key == item).Value</h3>
                        </div>
                        @foreach (var item2 in Model.AttributeValues.Where(p => p.Key == item))
                        {
                            <div class="col">
                                <div class="row g-3 ai-center jc-center">
                                    <div class="col-0">
                                        <p style="text-wrap: nowrap;">@item2.Value</p>
                                    </div>
                                    <div class="col-0">
                                        <input type="password" value="@item2.Value" class="secret" asp-for="@Model.FilterStorage[idx].Key" />
                                        <input type="checkbox" class="checkbox" checked="@Model.FilterStorage[idx].Value"
                                               asp-for="@Model.FilterStorage[idx].Value" />
                                    </div>
                                </div>
                            </div>

                            idx++;
                        }
                    </div>
                }
            }
        </form>

        <div class="row g-3 my-3 jc-center">
            <div class="col-0">
                <button class="button" form="filter"
                        formaction="/catalog/@Model.Category.Key?handler=Filter">
                    Filter
                </button>
            </div>
            <div class="col-0">
                <a class="button" href="/catalog/@Model.Category.Key">Clear</a>
            </div>
        </div>
    </div>
}

@if (Model.Products.Count > 0)
{
    <div class="container px-4 my-5">
        @foreach (var product in Model.Products)
        {
            <div class="row card my-5 ai-center jc-center">
                <div class="col-0">
                    <img class="img-sm" src="@product.Image" alt="@product.Product" />
                </div>

                <div class="col px-3">
                    <div class="row my-3">
                        <div class="col">
                            <h3 class="wrappable">@product.Product</h3>
                        </div>
                    </div>

                    <div class="row my-3">
                        <div class="col ta-end">
                            <p class="wrappable">@product.Price<i class="fa fa-hryvnia fa-sm"></i></p>
                        </div>
                    </div>

                    <div class="row my-3">
                        <div class="col">
                            <p class="wrappable">@product.ShortDescription</p>
                        </div>
                    </div>

                    <div class="row my-3 jc-center ai-center">
                        <div class="col-0 my-1 mx-3">
                            <a class="button" href="/product/@product.Key">View Product</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <div class="container px-4 my-5">
        <div class="row my-3">
            <div class="col ta-center">
                <p>Requested category have no one attached product yet</p>
            </div>
        </div>
    </div>
}

PL/Pages/Client/Orders.cshtml
@page
@model PL.Pages.Client.OrdersModel
@{
    ViewData["PgTitle"] = "Your Orders";
    Layout = "_Marketplace";
}

@using DAL.Enums

<div class="container px-4 my-5">
    <div class="row ai-center">
        <div class="col-0">
            <i class="fa fa-info-circle fa-2xl clr-g mx-3"></i>
        </div>

        <div class="col my-3">
            <h3>
                Here all active orders you have made. Watch ordering status here.
            </h3>
        </div>
    </div>

    <div class="row">
        <div class="col my-3 ta-end">
            <p>
                <strong>@Model.Products.Count</strong> active @(Model.Products.Count == 1 ? "order" : "orders")
            </p>
        </div>
    </div>
</div>

<div class="container px-4 my-5">
    @if (Model.Products.Count > 0)
    {
        @for (int idx = 0; idx < Model.Orders.Count; idx++)
        {
            <div class="card p-4">
                <div class="row">
                    <div class="col">
                        <p class="clr-b">@Model.Orders[idx].OrderNo</p>
                    </div>
                    <div class="col ta-end">
                        <p class="clr-b">@Model.Orders[idx].WhenOrdered</p>
                    </div>
                </div>
                <hr />
                <div class="row my-3 ai-center">
                    <div class="col min-sm">
                        <div class="row g-3">
                            <div class="col">
                                <h3>Product</h3>
                            </div>
                            <div class="col">
                                <p>@Model.Products[idx].Product</p>
                            </div>
                        </div>

                        <div class="row g-3">
                            <div class="col">
                                <h3>Price</h3>
                            </div>
                            <div class="col">
                                <p>@Model.Products[idx].Price</p>
                            </div>
                        </div>

                        <div class="row g-3">
                            <div class="col">
                                <h3>Ordered Amount</h3>
                            </div>
                            <div class="col">
                                <p>@Model.Orders[idx].Amount</p>
                            </div>
                        </div>

                        <div class="my-3">
                            <div class="row g-3">
                                <div class="col">
                                    <h3>Holder</h3>
                                </div>
                                <div class="col">
                                    <p>@ViewData["Holder"]</p>
                                </div>
                            </div>

                            <div class="row g-3">
                                <div class="col">
                                    <h3>Shippment address</h3>
                                </div>
                                <div class="col">
                                    <p>@Model.Orders[idx].Address</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row jc-center my-3 g-3">
                            <div class="col-0">
                                <a class="button" href="/product/@Model.Products[idx].Key">View Product</a>
                            </div>
                            <div class="col-0">
                                <form method="post">
                                    <input type="password" class="secret" value="@Model.Orders[idx].Key" name="key" />
                                    <button type="submit" class="button warning"
                                            asp-page-handler="Decline">
                                        Cancel Order
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="row my-3 g-3">
                            <div class="col ta-end">
                                <h3>Order Completion Status: </h3>
                            </div>
                            <div class="col">
                                @switch (Model.Orders[idx].Status)
                                {
                                    case OrderProcessingState.Registered:
                                        <p>Order generated successfully and waiting for review</p>
                                        break;
                                    case OrderProcessingState.Accepted:
                                        <p>The order has been processed and is waiting for transfer to the postal operator</p>
                                        break;
                                    case OrderProcessingState.Sent:
                                        <p>The order has been transferred to the postal operator and is in way to destination address</p>
                                        break;
                                    case OrderProcessingState.Delivered:
                                        <p>The package has delivered to destination and waiting for receiving</p>
                                        break;
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <div class="row">
            <div class="col ta-center">
                <p>No active orders</p>
            </div>
        </div>
    }
</div>